# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.15.2/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.15.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fmmarques/Documentos/Projects/bejeweled

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fmmarques/Documentos/Projects/bejeweled

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/cmake-3.15.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.15.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fmmarques/Documentos/Projects/bejeweled/CMakeFiles /home/fmmarques/Documentos/Projects/bejeweled/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fmmarques/Documentos/Projects/bejeweled/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bejeweled

# Build rule for target.
bejeweled: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bejeweled
.PHONY : bejeweled

# fast build rule for target.
bejeweled/fast:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/build
.PHONY : bejeweled/fast

#=============================================================================
# Target rules for targets named assets_directory

# Build rule for target.
assets_directory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assets_directory
.PHONY : assets_directory

# fast build rule for target.
assets_directory/fast:
	$(MAKE) -f CMakeFiles/assets_directory.dir/build.make CMakeFiles/assets_directory.dir/build
.PHONY : assets_directory/fast

#=============================================================================
# Target rules for targets named state_machine_tests

# Build rule for target.
state_machine_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 state_machine_tests
.PHONY : state_machine_tests

# fast build rule for target.
state_machine_tests/fast:
	$(MAKE) -f dependencies/yage/CMakeFiles/state_machine_tests.dir/build.make dependencies/yage/CMakeFiles/state_machine_tests.dir/build
.PHONY : state_machine_tests/fast

#=============================================================================
# Target rules for targets named yage

# Build rule for target.
yage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yage
.PHONY : yage

# fast build rule for target.
yage/fast:
	$(MAKE) -f dependencies/yage/CMakeFiles/yage.dir/build.make dependencies/yage/CMakeFiles/yage.dir/build
.PHONY : yage/fast

#=============================================================================
# Target rules for targets named graphics_tests

# Build rule for target.
graphics_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphics_tests
.PHONY : graphics_tests

# fast build rule for target.
graphics_tests/fast:
	$(MAKE) -f dependencies/yage/CMakeFiles/graphics_tests.dir/build.make dependencies/yage/CMakeFiles/graphics_tests.dir/build
.PHONY : graphics_tests/fast

#=============================================================================
# Target rules for targets named widgets_tests

# Build rule for target.
widgets_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 widgets_tests
.PHONY : widgets_tests

# fast build rule for target.
widgets_tests/fast:
	$(MAKE) -f dependencies/yage/CMakeFiles/widgets_tests.dir/build.make dependencies/yage/CMakeFiles/widgets_tests.dir/build
.PHONY : widgets_tests/fast

#=============================================================================
# Target rules for targets named all_tests

# Build rule for target.
all_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_tests
.PHONY : all_tests

# fast build rule for target.
all_tests/fast:
	$(MAKE) -f dependencies/yage/CMakeFiles/all_tests.dir/build.make dependencies/yage/CMakeFiles/all_tests.dir/build
.PHONY : all_tests/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f dependencies/yage/dependencies/googletest/googletest/CMakeFiles/gtest.dir/build.make dependencies/yage/dependencies/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f dependencies/yage/dependencies/googletest/googletest/CMakeFiles/gtest_main.dir/build.make dependencies/yage/dependencies/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/bejeweled.o: src/bejeweled.cpp.o

.PHONY : src/bejeweled.o

# target to build an object file
src/bejeweled.cpp.o:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/bejeweled.cpp.o
.PHONY : src/bejeweled.cpp.o

src/bejeweled.i: src/bejeweled.cpp.i

.PHONY : src/bejeweled.i

# target to preprocess a source file
src/bejeweled.cpp.i:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/bejeweled.cpp.i
.PHONY : src/bejeweled.cpp.i

src/bejeweled.s: src/bejeweled.cpp.s

.PHONY : src/bejeweled.s

# target to generate assembly for a file
src/bejeweled.cpp.s:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/bejeweled.cpp.s
.PHONY : src/bejeweled.cpp.s

src/states/base_game.o: src/states/base_game.cpp.o

.PHONY : src/states/base_game.o

# target to build an object file
src/states/base_game.cpp.o:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/states/base_game.cpp.o
.PHONY : src/states/base_game.cpp.o

src/states/base_game.i: src/states/base_game.cpp.i

.PHONY : src/states/base_game.i

# target to preprocess a source file
src/states/base_game.cpp.i:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/states/base_game.cpp.i
.PHONY : src/states/base_game.cpp.i

src/states/base_game.s: src/states/base_game.cpp.s

.PHONY : src/states/base_game.s

# target to generate assembly for a file
src/states/base_game.cpp.s:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/states/base_game.cpp.s
.PHONY : src/states/base_game.cpp.s

src/states/main_menu.o: src/states/main_menu.cpp.o

.PHONY : src/states/main_menu.o

# target to build an object file
src/states/main_menu.cpp.o:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/states/main_menu.cpp.o
.PHONY : src/states/main_menu.cpp.o

src/states/main_menu.i: src/states/main_menu.cpp.i

.PHONY : src/states/main_menu.i

# target to preprocess a source file
src/states/main_menu.cpp.i:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/states/main_menu.cpp.i
.PHONY : src/states/main_menu.cpp.i

src/states/main_menu.s: src/states/main_menu.cpp.s

.PHONY : src/states/main_menu.s

# target to generate assembly for a file
src/states/main_menu.cpp.s:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/states/main_menu.cpp.s
.PHONY : src/states/main_menu.cpp.s

src/widgets/grid.o: src/widgets/grid.cpp.o

.PHONY : src/widgets/grid.o

# target to build an object file
src/widgets/grid.cpp.o:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/widgets/grid.cpp.o
.PHONY : src/widgets/grid.cpp.o

src/widgets/grid.i: src/widgets/grid.cpp.i

.PHONY : src/widgets/grid.i

# target to preprocess a source file
src/widgets/grid.cpp.i:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/widgets/grid.cpp.i
.PHONY : src/widgets/grid.cpp.i

src/widgets/grid.s: src/widgets/grid.cpp.s

.PHONY : src/widgets/grid.s

# target to generate assembly for a file
src/widgets/grid.cpp.s:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/widgets/grid.cpp.s
.PHONY : src/widgets/grid.cpp.s

src/widgets/grid_generators.o: src/widgets/grid_generators.cpp.o

.PHONY : src/widgets/grid_generators.o

# target to build an object file
src/widgets/grid_generators.cpp.o:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/widgets/grid_generators.cpp.o
.PHONY : src/widgets/grid_generators.cpp.o

src/widgets/grid_generators.i: src/widgets/grid_generators.cpp.i

.PHONY : src/widgets/grid_generators.i

# target to preprocess a source file
src/widgets/grid_generators.cpp.i:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/widgets/grid_generators.cpp.i
.PHONY : src/widgets/grid_generators.cpp.i

src/widgets/grid_generators.s: src/widgets/grid_generators.cpp.s

.PHONY : src/widgets/grid_generators.s

# target to generate assembly for a file
src/widgets/grid_generators.cpp.s:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/widgets/grid_generators.cpp.s
.PHONY : src/widgets/grid_generators.cpp.s

src/widgets/jewel.o: src/widgets/jewel.cpp.o

.PHONY : src/widgets/jewel.o

# target to build an object file
src/widgets/jewel.cpp.o:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/widgets/jewel.cpp.o
.PHONY : src/widgets/jewel.cpp.o

src/widgets/jewel.i: src/widgets/jewel.cpp.i

.PHONY : src/widgets/jewel.i

# target to preprocess a source file
src/widgets/jewel.cpp.i:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/widgets/jewel.cpp.i
.PHONY : src/widgets/jewel.cpp.i

src/widgets/jewel.s: src/widgets/jewel.cpp.s

.PHONY : src/widgets/jewel.s

# target to generate assembly for a file
src/widgets/jewel.cpp.s:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/widgets/jewel.cpp.s
.PHONY : src/widgets/jewel.cpp.s

src/widgets/score.o: src/widgets/score.cpp.o

.PHONY : src/widgets/score.o

# target to build an object file
src/widgets/score.cpp.o:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/widgets/score.cpp.o
.PHONY : src/widgets/score.cpp.o

src/widgets/score.i: src/widgets/score.cpp.i

.PHONY : src/widgets/score.i

# target to preprocess a source file
src/widgets/score.cpp.i:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/widgets/score.cpp.i
.PHONY : src/widgets/score.cpp.i

src/widgets/score.s: src/widgets/score.cpp.s

.PHONY : src/widgets/score.s

# target to generate assembly for a file
src/widgets/score.cpp.s:
	$(MAKE) -f CMakeFiles/bejeweled.dir/build.make CMakeFiles/bejeweled.dir/src/widgets/score.cpp.s
.PHONY : src/widgets/score.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... bejeweled"
	@echo "... rebuild_cache"
	@echo "... assets_directory"
	@echo "... state_machine_tests"
	@echo "... yage"
	@echo "... graphics_tests"
	@echo "... widgets_tests"
	@echo "... all_tests"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/bejeweled.o"
	@echo "... src/bejeweled.i"
	@echo "... src/bejeweled.s"
	@echo "... src/states/base_game.o"
	@echo "... src/states/base_game.i"
	@echo "... src/states/base_game.s"
	@echo "... src/states/main_menu.o"
	@echo "... src/states/main_menu.i"
	@echo "... src/states/main_menu.s"
	@echo "... src/widgets/grid.o"
	@echo "... src/widgets/grid.i"
	@echo "... src/widgets/grid.s"
	@echo "... src/widgets/grid_generators.o"
	@echo "... src/widgets/grid_generators.i"
	@echo "... src/widgets/grid_generators.s"
	@echo "... src/widgets/jewel.o"
	@echo "... src/widgets/jewel.i"
	@echo "... src/widgets/jewel.s"
	@echo "... src/widgets/score.o"
	@echo "... src/widgets/score.i"
	@echo "... src/widgets/score.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

